version: "3"

# NEEDs for production, volumes for backup data
# NEEDs for production my.cnf final

services:
  database: 
    image: mariadb:10.8.2
    restart: always
    networks:
      - back-rail
    environment:
      - MARIADB_ROOT_PASSWORD=password
    # volumes:
    #   - ./my.cnf:/etc/mysql/my.cnf
  
  adminer:
    image: adminer
    restart: always
    networks:
      - back-rail
    ports:
      - "8080:8080/tcp"
    depends_on:
      - database

  phpfpm:
    image: php:8.1-fpm-bullseye
    networks:
      - back-rail
    volumes:
      - ./php_logs:/var/log/fpm-php.www.log:rw
      - ./html:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:1.22.1
    networks:
      - back-rail
    volumes:
      - ./nginx_logs:/var/log/nginx:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80/tcp"
    volumes_from:
      - phpfpm

networks:
  back-rail:
    driver: bridge